site_name: Monitax
theme: 
  name: material
nav:
  - Home: index.md
  - CLI: cli.md    
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  